
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktable-app
  labels:
    app: ktable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktable-app
  template:
    metadata:
      labels:
        app: ktable-app
    spec:
      containers:
        - name: ktable-app
          image: koushindra/ktable-app:latest
          resources:
            requests:
              cpu: 1m
            limits:
              cpu: 50m