apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ktable-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ktable-app
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
      policies:
        - type: Percent
          value: 100
          periodSeconds: 20
