apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-manual-ebs-pv
  labels:
    type: amazon-ebs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-02cb752015464974b
    fsType: ext4  # or another filesystem type if you prefer
  persistentVolumeReclaimPolicy: Retain